### ISSUE TITLE
Old versions items.dat

### ISSUE THREAD

**Issue by Lebedev21** [DefaultO/Growtopia-Versions#5]
Hey. 
Is there any possibility of getting the items.dat file from the **really** old versions (like the first release here 1.44)?

**Comment by DefaultO** [comment]
A clean installation would give you the oldschool rttx texture files. That's for sure. 

I am not sure though if you will be able to generate the items.dat without modifying the game client. It is located in ``...\Growtopia\cache``, and appears once you have connected to the game server. You probably will have to figure out how the game does it. So you can replicate it yourself.

If in order to generate the items.dat you need information from the server. Then no.

**Comment by Lebedev21** [comment]
Alright thanks.
